# services — Service Protocol interfaces
from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class ICombatService(Protocol):
    """Interface for combat operations."""

    def process_turn(self, attacker, defender, rng,
                     forced_ability: dict | None = None) -> dict: ...


@runtime_checkable
class INeedsService(Protocol):
    """Interface for needs system operations."""

    def create_needs(self) -> list: ...
    def update(self, needs: list, is_sleeping: bool = False) -> None: ...
    def get_priority(self, needs: list): ...
    def fill(self, need, dt: float) -> bool: ...


@runtime_checkable
class IEntityFactory(Protocol):
    """Interface for entity creation."""

    def create_player(self): ...
    def create_all_npcs(self) -> list: ...
    def get_sprite_path(self, entity_id: str) -> str | None: ...


@runtime_checkable
class IInventoryService(Protocol):
    """Interface for inventory management."""

    def get_inventory(self, entity_id: str): ...
    def add_item(self, entity_id: str, item, qty: int = 1) -> bool: ...
    def remove_item(self, entity_id: str, item_id: str, qty: int = 1) -> bool: ...
    def use_consumable(self, entity_id: str, item_id: str): ...
    def carried_weight(self, entity_id: str) -> float: ...
    def capacity(self, str_stat: int) -> float: ...
    def is_encumbered(self, entity_id: str, str_stat: int) -> bool: ...
    def serialize_all(self) -> dict: ...


@runtime_checkable
class IEquipmentService(Protocol):
    """Interface for equipment management."""

    def get_equipment(self, entity_id: str): ...
    def equip(self, entity_id: str, item, slot_name: str, inv_svc=None): ...
    def unequip(self, entity_id: str, slot_name: str, inv_svc=None): ...
    def gear_mods(self, entity_id: str) -> dict: ...
    def weapon_profile(self, entity_id: str): ...
    def serialize_all(self) -> dict: ...
